[package]
name = "rShip"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
device_query = "1.1.1"

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_System_Console"
]